name: Line Counter
run-name: ${{ github.head_ref }} line count
on: [pull_request]
permissions:
  pull-requests: write
  contents: read
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Calculate lines
        run: |
          echo "$(git for-each-ref --format='%(refname:short)' refs/remotes/origin)"
          for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin); do
            git checkout $branch
            echo "Branch $branch:" >> out.txt
            echo "ðŸ“Š Repo Stats After This PR:" >> out.txt
            echo "- Total files: $(find . -type f -not -path './.git/*' | wc -l)" >> out.txt
            echo "- Total lines of code: $(find . -type f -not -path './.git/*' | xargs wc -l | sed -nE 's/\s+([0-9]+) total/\1/p')" >> out.txt
          done
      - name: View lines
        run: |
          cat out.txt
      - name: Comment on PR
        run: |
          gh pr comment "$PR_URL" -F out.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Notify Google Chat
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          additionalSections: '[{"header": "Line count", "collapsible": false, "widgets": [{"text": "$(cat out.txt)"}}] }]'
